export const MANAGED_INSTRUCTIONS_BEGIN = "<!-- BEGIN TROPASS MCP INSTRUCTIONS -->";
export const MANAGED_INSTRUCTIONS_END = "<!-- END TROPASS MCP INSTRUCTIONS -->";

export const TROPASS_MCP_INSTRUCTIONS = `# Tropass MCP Instructions

Use the Tropass MCP server to call ML models.

## Tool discovery

- Call \`tools/list\` only on first Tropass use in the session, when \`initialize.result.capabilities.tools.listChanged\` is \`true\`, after token/environment changes, or after an unknown tool error.
- Do not call \`tools/list\` before every model call.
- Do not rely on memorized tool names. Tool names are generated by the gateway.

## Tool selection

- Select models by \`title\`, \`description\`, and \`inputSchema\`.
- If several tools match equally, ask the user which model to use.
- If the requested model is missing, refresh the tool list once before concluding it is unavailable.

## Arguments

- Validate arguments against \`inputSchema\`.
- Send only properties defined in the schema.
- Required fields must be present.
- Respect \`enum\`, \`minimum\`, and \`maximum\`.
- For file-like inputs, pass arrays of existing Tropass/S3 file URLs.
- Do not pass local file paths or arbitrary external URLs as file inputs.

## Results

- Prefer \`structuredContent\` as the source of truth.
- Treat text \`content\` as serialized fallback JSON.
- If \`isError\` is true, surface the error directly.
- Do not retry rate-limit errors in a loop.
`;

export function buildInstructionContent(client) {
  if (client === "cursor") {
    return `---
description: Use Tropass MCP for ML model calls
alwaysApply: true
---

${TROPASS_MCP_INSTRUCTIONS}`;
  }
  if (client === "claude-desktop") {
    return `${TROPASS_MCP_INSTRUCTIONS}
Add these instructions to your Claude project or custom instructions together with the Tropass MCP server config.
`;
  }
  return TROPASS_MCP_INSTRUCTIONS;
}

